name: Build and Push Docker Image ğŸš€

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: shlomi10/pdf-trivia-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ”‘ Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: ğŸ—ï¸ Build Docker image with build number tag and latest
        run: |
          IMAGE_TAG=${{ github.run_number }}
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest

      - name: ğŸ“¤ Push Docker image with build tag and latest
        run: |
          IMAGE_TAG=${{ github.run_number }}
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest
